### PR TITLE
[Screencast]: Register for CDP events when using with js-debug proxy

### LINKED ISSUE #687: Standalone screencast not working when attached via js-debug
**Environment (please complete the following information):**
 - OS (*e.g.,* Windows 10): Win 10
 - Extension version (*e.g.,* 1.2.3): 1.4.1

**Describe the bug:**
When launching edge via a launch.json debug session, attaching the DevTools works, but subsequently launching the screencast results in a blank display where the screencast content should be.

**Repro steps:**
1. Add a config to launch.json to launch `pwa-msedge`
2. Open DevTools
3. Toggle Screencast

**Expected behavior:**
The page content appears in the screencast

**Additional context:**
Looks like this is because the screencast creates a separate websocket connection that gets proxied through js-debug, but does not request to receive events for various CDP domains. This results in the screencast frame events never making it to the screencast to be displayed.

### PR DESCRIPTION
**Pull request by antross**
Fix #687 

Screencast frames were not being received because the corresponding events were not getting forwarded from js-debug over the proxied CDP connection. Sending the js-debug specific request for events fixes the issue per https://github.com/microsoft/vscode-js-debug/blob/main/CDP_SHARE.md, aligning the screencast panel with the existing behavior for the devtools panel.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -127,15 +127,15 @@ export function activate(context: vscode.ExtensionContext): void {
 
     context.subscriptions.push(vscode.commands.registerCommand(
         `${SETTINGS_VIEW_NAME}.toggleScreencast`,
-        (target?: CDPTarget) => {
+        (target?: CDPTarget, isJsDebugProxiedCDPConnection = false) => {
```
Comment (mliao95) [inline src/extension.ts:130]: Is there a purpose of defaulting `isJsDebugProxiedCDPConnection` to false here if we already do it in `ScreencastPanel.createOrShow`?

**Review by mliao95 — APPROVED** [review]
LGTM with a question.

File: src/extension.ts (hunk 1 above)
Comment (antross) [reply src/extension.ts:130]: Not particularly. We could just make this an optional param. No strong preference on my part.
